@startuml
left to right direction
skinparam handwritten true
skinparam usecase{
    BackgroundColor pink
    BorderColor pastel blue
}
图书管理员 as admin
会员 as vip
非会员 as nvip
rectangle 图书管理系统{
    admin --> (管理书籍)
    admin --> (管理会员机制)
    admin --> (登记借/还书)
    admin --> (维护读者信息)
    vip --> (借阅书籍)
    vip --> (归还书籍)
    vip --> (预约书籍)
    vip --> (查询借阅记录)
    nvip --> (查阅书籍)
}
@enduml