@startuml
package "图书管理系统"{
    class 图书{
        __private__
        -long 编号
        -int 类别
        -String 书名
        -String 出版社
        -Date 年份
        -String 作者
        -float 价格
        -int 总藏书量
        -int 库存
        __省略getter/setter方法__
    }

    class 书籍类型{
        __private__
        -int 编号
        -String 类型
        __省略getter/setter方法__
    }

    class 借书证{
            __private__
            -int 借书证号
            -String 姓名
            -String 类别(是否会员)
            __省略getter/setter方法__
    }

    class 管理员{
            __private__
            -int 管理员ID
            -String 姓名
            -String 密码
            -String 联系方式
            __省略getter/setter方法__
    }

    class 记录{
            __private__
            -int 书号
            -int 借书证号
            -Date 借期
            -Date 还期
            -int 经手人(图书管理员ID)
            __省略getter/setter方法__
    }

    图书 *-- 书籍类型 : 一本书许多类型
    图书 "n" -- "1" 记录 : 登记借书图书
    记录 "1" -- "n" 借书证 : 登记借书者
    管理员 "n" -- "n" 借书证 : 维护读者信息
    管理员 "n" -- "n" 图书 : 维护图书信息
    管理员 "n" -- "n" 记录 : 维护借书记录

}
@enduml